[package]
name = "lone-ranger"
license = "MIT"
version = "1.0.2"
readme = "README.MD"
authors = ["DCjanus <DCjanus@dcjanus.com>"]
description = "Subtitles downloader"
homepage = "https://github.com/DCjanus/lone-ranger"
repository = "https://github.com/DCjanus/lone-ranger.git"

[dependencies]
url = "1.7"
sha1 = {version = "0.6", features = ["std"]}
clap = "2.32"
reqwest = "0.9"
failure = "0.1"
threadpool = "1.7"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[[bin]]
name = "ranger"
path = "src/main.rs"
test = false
doc = false
